const fieldOffices = [
    { state: "Alabama", offices: ["Birmingham", "Mobile"] },
    { state: "Alaska", offices: ["Anchorage"] },
    { state: "Arizona", offices: ["Phoenix"] },
    { state: "Arkansas", offices: ["Little Rock"] },
    { state: "California", offices: ["Los Angeles", "San Francisco", "Sacramento", "San Diego"] },
    { state: "Colorado", offices: ["Denver"] },
    { state: "Connecticut", offices: ["New Haven"] },
    { state: "Delaware", offices: ["Wilmington"] },
    { state: "District of Columbia", offices: ["Washington D.C."] },
    { state: "Florida", offices: ["Miami", "Tampa", "Jacksonville", "Orlando"] },
    { state: "Georgia", offices: ["Atlanta"] },
    { state: "Hawaii", offices: ["Honolulu"] },
    { state: "Idaho", offices: ["Boise"] },
    { state: "Illinois", offices: ["Chicago"] },
    { state: "Indiana", offices: ["Indianapolis"] },
    { state: "Iowa", offices: ["Des Moines"] },
    { state: "Kansas", offices: ["Kansas City"] },
    { state: "Kentucky", offices: ["Louisville"] },
    { state: "Louisiana", offices: ["New Orleans"] },
    { state: "Maine", offices: ["Portland"] },
    { state: "Maryland", offices: ["Baltimore"] },
    { state: "Massachusetts", offices: ["Boston"] },
    { state: "Michigan", offices: ["Detroit"] },
    { state: "Minnesota", offices: ["Minneapolis"] },
    { state: "Mississippi", offices: ["Jackson"] },
    { state: "Missouri", offices: ["St. Louis"] },
    { state: "Montana", offices: ["Billings"] },
    { state: "Nebraska", offices: ["Omaha"] },
    { state: "Nevada", offices: ["Las Vegas"] },
    { state: "New Hampshire", offices: ["Manchester"] },
    { state: "New Jersey", offices: ["Newark"] },
    { state: "New Mexico", offices: ["Albuquerque"] },
    { state: "New York", offices: ["New York", "Albany"] },
    { state: "North Carolina", offices: ["Charlotte", "Raleigh"] },
    { state: "North Dakota", offices: ["Fargo"] },
    { state: "Ohio", offices: ["Cleveland", "Cincinnati"] },
    { state: "Oklahoma", offices: ["Oklahoma City"] },
    { state: "Oregon", offices: ["Portland"] },
    { state: "Pennsylvania", offices: ["Philadelphia", "Pittsburgh"] },
    { state: "Rhode Island", offices: ["Providence"] },
    { state: "South Carolina", offices: ["Charleston", "Columbia"] },
    { state: "South Dakota", offices: ["Sioux Falls"] },
    { state: "Tennessee", offices: ["Nashville"] },
    { state: "Texas", offices: ["Dallas", "Houston", "San Antonio", "Austin"] },
    { state: "Utah", offices: ["Salt Lake City"] },
    { state: "Vermont", offices: ["Burlington"] },
    { state: "Virginia", offices: ["Richmond"] },
    { state: "Washington", offices: ["Seattle"] },
    { state: "West Virginia", offices: ["Charleston"] },
    { state: "Wisconsin", offices: ["Milwaukee"] },
    { state: "Wyoming", offices: ["Cheyenne"] }
];

export default fieldOffices;